//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/InputSystem/KBMandController.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @KBMandController: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @KBMandController()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""KBMandController"",
    ""maps"": [
        {
            ""name"": ""ActivePlayer"",
            ""id"": ""e344afa6-c2c4-4131-a670-8e7df98dac46"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""223a7065-8f3b-4ea5-b0ea-ed09d9722802"",
                    ""expectedControlType"": ""Stick"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Run"",
                    ""type"": ""Button"",
                    ""id"": ""c8e347f1-b8a8-4387-90b8-90a0dc10dfb9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Look"",
                    ""type"": ""Value"",
                    ""id"": ""65bfea7d-320f-41a2-9a69-b17bef38263a"",
                    ""expectedControlType"": ""Stick"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Aim"",
                    ""type"": ""Value"",
                    ""id"": ""a6d3b826-fe87-4bd3-b38b-e9ff7991f778"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Attack"",
                    ""type"": ""Button"",
                    ""id"": ""1edce362-abf0-4eeb-944d-d76c5dd90fcd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Interact"",
                    ""type"": ""Value"",
                    ""id"": ""1208abd1-2b87-4e20-9e08-0fea7551bd64"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Heal"",
                    ""type"": ""Value"",
                    ""id"": ""8863d1d2-a7ba-4163-bb8d-8203421c8497"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Swap"",
                    ""type"": ""Value"",
                    ""id"": ""bcda6efb-9e1c-4017-87a6-e6cf17baf3ab"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Ping"",
                    ""type"": ""Button"",
                    ""id"": ""d54154b7-8aa9-449b-b4c9-8ce8432d222e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""032f4b9e-a5fa-426c-b380-751b666e3d3f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Crouch"",
                    ""type"": ""Button"",
                    ""id"": ""d2855d0e-5fbe-4fda-abc9-33bba4ed97f0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""1171855c-4711-4cef-ace3-e4faedc24b99"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""ControllerPlayer"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cb4fe1e3-d0ed-4415-b6a8-d3a64a812d81"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""ControllerPlayer"",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d1e24edf-0331-46b4-84cf-d8879a670008"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""ControllerPlayer"",
                    ""action"": ""Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""708bb914-859c-429b-afa3-95fe360296c0"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""ControllerPlayer"",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""35811f0b-28ee-4e10-88d9-ee30ea45de0e"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""ControllerPlayer"",
                    ""action"": ""Heal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""085f7e15-8d29-4657-8f8c-7a9c6c106a0e"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""ControllerPlayer"",
                    ""action"": ""Swap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b60275c3-4f0e-49f6-8c07-976c269e9a87"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""ControllerPlayer"",
                    ""action"": ""Ping"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dfb730ba-7319-4fb6-84d0-6cb95294f103"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""ControllerPlayer"",
                    ""action"": ""Aim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1d1eae53-70a1-48b9-a80e-734366dd0fd2"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""ControllerPlayer"",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1a4314a2-73ad-41be-9607-45446ca6c08f"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Crouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8c029f3b-5ff6-43fc-b114-980ce30759ff"",
                    ""path"": ""<Gamepad>/leftStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""ControllerPlayer"",
                    ""action"": ""Run"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""ManagerPlayer"",
            ""id"": ""37c2e037-d546-492b-bb0f-1d0dff6487dd"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""83bd3c8e-9bf8-4ae9-afc2-eeb82c4eed99"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""87c2f43a-e4e3-4fb2-896d-58dc1170f903"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Cycle"",
                    ""type"": ""Button"",
                    ""id"": ""a84d88f8-9606-41b5-a91f-c3bc258f5930"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Ping"",
                    ""type"": ""Button"",
                    ""id"": ""79739e92-c6fe-42f2-a949-d7d15892974d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Zoom"",
                    ""type"": ""Value"",
                    ""id"": ""cd493a75-06fd-406c-884f-7ed611163781"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": ""NormalizeVector2"",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Deselect"",
                    ""type"": ""Button"",
                    ""id"": ""1b70c525-d8c1-41f6-8404-6b2a556230da"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""12dfa735-70ec-4077-a9e8-f453604ecb8e"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""d4df315f-d800-44dd-ac5c-876c2f06dfa8"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KBMPlayer"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""662c4ad2-94c2-47e7-9ef9-ba94ff9e0677"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KBMPlayer"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""ecd153b9-df87-46a9-9764-234c0caf1698"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KBMPlayer"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""da328469-3455-45cb-afbc-d76ea6711748"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KBMPlayer"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""5bf77527-e5d6-431b-8fc9-d854b20034e9"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KBMPlayer"",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""216b0c5d-18b6-4eb4-9b9c-0745142ad9ef"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KBMPlayer"",
                    ""action"": ""Cycle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0ce70e47-3e1e-4faf-beb0-af3d270c5221"",
                    ""path"": ""<Mouse>/middleButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KBMPlayer"",
                    ""action"": ""Ping"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e6067caa-6518-42eb-b523-daa6f536c026"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": ""NormalizeVector2"",
                    ""groups"": ""KBMPlayer"",
                    ""action"": ""Zoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cd5e8832-b112-4ee3-a687-a506b51b7673"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KBMPlayer"",
                    ""action"": ""Deselect"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""StorySceneConfirms"",
            ""id"": ""5de4e98a-c35b-4439-822b-51b17cbec564"",
            ""actions"": [
                {
                    ""name"": ""GamepadConfirm"",
                    ""type"": ""Button"",
                    ""id"": ""96dba6c7-e198-4a48-a110-e512a1a5fc62"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""EnterConfirm"",
                    ""type"": ""Button"",
                    ""id"": ""9a86cd0b-4d9d-48ac-b73b-16ef6f4e7587"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""c79a7e02-0be9-4726-9a4e-8b459bc026cd"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""ControllerPlayer;KBMPlayer"",
                    ""action"": ""GamepadConfirm"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""24bc5a85-29e6-4a0b-b88b-a9fb2e1b5360"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KBMPlayer;ControllerPlayer"",
                    ""action"": ""EnterConfirm"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""ControllerPlayer"",
            ""bindingGroup"": ""ControllerPlayer"",
            ""devices"": []
        },
        {
            ""name"": ""KBMPlayer"",
            ""bindingGroup"": ""KBMPlayer"",
            ""devices"": []
        }
    ]
}");
        // ActivePlayer
        m_ActivePlayer = asset.FindActionMap("ActivePlayer", throwIfNotFound: true);
        m_ActivePlayer_Move = m_ActivePlayer.FindAction("Move", throwIfNotFound: true);
        m_ActivePlayer_Run = m_ActivePlayer.FindAction("Run", throwIfNotFound: true);
        m_ActivePlayer_Look = m_ActivePlayer.FindAction("Look", throwIfNotFound: true);
        m_ActivePlayer_Aim = m_ActivePlayer.FindAction("Aim", throwIfNotFound: true);
        m_ActivePlayer_Attack = m_ActivePlayer.FindAction("Attack", throwIfNotFound: true);
        m_ActivePlayer_Interact = m_ActivePlayer.FindAction("Interact", throwIfNotFound: true);
        m_ActivePlayer_Heal = m_ActivePlayer.FindAction("Heal", throwIfNotFound: true);
        m_ActivePlayer_Swap = m_ActivePlayer.FindAction("Swap", throwIfNotFound: true);
        m_ActivePlayer_Ping = m_ActivePlayer.FindAction("Ping", throwIfNotFound: true);
        m_ActivePlayer_Jump = m_ActivePlayer.FindAction("Jump", throwIfNotFound: true);
        m_ActivePlayer_Crouch = m_ActivePlayer.FindAction("Crouch", throwIfNotFound: true);
        // ManagerPlayer
        m_ManagerPlayer = asset.FindActionMap("ManagerPlayer", throwIfNotFound: true);
        m_ManagerPlayer_Move = m_ManagerPlayer.FindAction("Move", throwIfNotFound: true);
        m_ManagerPlayer_Interact = m_ManagerPlayer.FindAction("Interact", throwIfNotFound: true);
        m_ManagerPlayer_Cycle = m_ManagerPlayer.FindAction("Cycle", throwIfNotFound: true);
        m_ManagerPlayer_Ping = m_ManagerPlayer.FindAction("Ping", throwIfNotFound: true);
        m_ManagerPlayer_Zoom = m_ManagerPlayer.FindAction("Zoom", throwIfNotFound: true);
        m_ManagerPlayer_Deselect = m_ManagerPlayer.FindAction("Deselect", throwIfNotFound: true);
        // StorySceneConfirms
        m_StorySceneConfirms = asset.FindActionMap("StorySceneConfirms", throwIfNotFound: true);
        m_StorySceneConfirms_GamepadConfirm = m_StorySceneConfirms.FindAction("GamepadConfirm", throwIfNotFound: true);
        m_StorySceneConfirms_EnterConfirm = m_StorySceneConfirms.FindAction("EnterConfirm", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // ActivePlayer
    private readonly InputActionMap m_ActivePlayer;
    private List<IActivePlayerActions> m_ActivePlayerActionsCallbackInterfaces = new List<IActivePlayerActions>();
    private readonly InputAction m_ActivePlayer_Move;
    private readonly InputAction m_ActivePlayer_Run;
    private readonly InputAction m_ActivePlayer_Look;
    private readonly InputAction m_ActivePlayer_Aim;
    private readonly InputAction m_ActivePlayer_Attack;
    private readonly InputAction m_ActivePlayer_Interact;
    private readonly InputAction m_ActivePlayer_Heal;
    private readonly InputAction m_ActivePlayer_Swap;
    private readonly InputAction m_ActivePlayer_Ping;
    private readonly InputAction m_ActivePlayer_Jump;
    private readonly InputAction m_ActivePlayer_Crouch;
    public struct ActivePlayerActions
    {
        private @KBMandController m_Wrapper;
        public ActivePlayerActions(@KBMandController wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_ActivePlayer_Move;
        public InputAction @Run => m_Wrapper.m_ActivePlayer_Run;
        public InputAction @Look => m_Wrapper.m_ActivePlayer_Look;
        public InputAction @Aim => m_Wrapper.m_ActivePlayer_Aim;
        public InputAction @Attack => m_Wrapper.m_ActivePlayer_Attack;
        public InputAction @Interact => m_Wrapper.m_ActivePlayer_Interact;
        public InputAction @Heal => m_Wrapper.m_ActivePlayer_Heal;
        public InputAction @Swap => m_Wrapper.m_ActivePlayer_Swap;
        public InputAction @Ping => m_Wrapper.m_ActivePlayer_Ping;
        public InputAction @Jump => m_Wrapper.m_ActivePlayer_Jump;
        public InputAction @Crouch => m_Wrapper.m_ActivePlayer_Crouch;
        public InputActionMap Get() { return m_Wrapper.m_ActivePlayer; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ActivePlayerActions set) { return set.Get(); }
        public void AddCallbacks(IActivePlayerActions instance)
        {
            if (instance == null || m_Wrapper.m_ActivePlayerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_ActivePlayerActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @Run.started += instance.OnRun;
            @Run.performed += instance.OnRun;
            @Run.canceled += instance.OnRun;
            @Look.started += instance.OnLook;
            @Look.performed += instance.OnLook;
            @Look.canceled += instance.OnLook;
            @Aim.started += instance.OnAim;
            @Aim.performed += instance.OnAim;
            @Aim.canceled += instance.OnAim;
            @Attack.started += instance.OnAttack;
            @Attack.performed += instance.OnAttack;
            @Attack.canceled += instance.OnAttack;
            @Interact.started += instance.OnInteract;
            @Interact.performed += instance.OnInteract;
            @Interact.canceled += instance.OnInteract;
            @Heal.started += instance.OnHeal;
            @Heal.performed += instance.OnHeal;
            @Heal.canceled += instance.OnHeal;
            @Swap.started += instance.OnSwap;
            @Swap.performed += instance.OnSwap;
            @Swap.canceled += instance.OnSwap;
            @Ping.started += instance.OnPing;
            @Ping.performed += instance.OnPing;
            @Ping.canceled += instance.OnPing;
            @Jump.started += instance.OnJump;
            @Jump.performed += instance.OnJump;
            @Jump.canceled += instance.OnJump;
            @Crouch.started += instance.OnCrouch;
            @Crouch.performed += instance.OnCrouch;
            @Crouch.canceled += instance.OnCrouch;
        }

        private void UnregisterCallbacks(IActivePlayerActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @Run.started -= instance.OnRun;
            @Run.performed -= instance.OnRun;
            @Run.canceled -= instance.OnRun;
            @Look.started -= instance.OnLook;
            @Look.performed -= instance.OnLook;
            @Look.canceled -= instance.OnLook;
            @Aim.started -= instance.OnAim;
            @Aim.performed -= instance.OnAim;
            @Aim.canceled -= instance.OnAim;
            @Attack.started -= instance.OnAttack;
            @Attack.performed -= instance.OnAttack;
            @Attack.canceled -= instance.OnAttack;
            @Interact.started -= instance.OnInteract;
            @Interact.performed -= instance.OnInteract;
            @Interact.canceled -= instance.OnInteract;
            @Heal.started -= instance.OnHeal;
            @Heal.performed -= instance.OnHeal;
            @Heal.canceled -= instance.OnHeal;
            @Swap.started -= instance.OnSwap;
            @Swap.performed -= instance.OnSwap;
            @Swap.canceled -= instance.OnSwap;
            @Ping.started -= instance.OnPing;
            @Ping.performed -= instance.OnPing;
            @Ping.canceled -= instance.OnPing;
            @Jump.started -= instance.OnJump;
            @Jump.performed -= instance.OnJump;
            @Jump.canceled -= instance.OnJump;
            @Crouch.started -= instance.OnCrouch;
            @Crouch.performed -= instance.OnCrouch;
            @Crouch.canceled -= instance.OnCrouch;
        }

        public void RemoveCallbacks(IActivePlayerActions instance)
        {
            if (m_Wrapper.m_ActivePlayerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IActivePlayerActions instance)
        {
            foreach (var item in m_Wrapper.m_ActivePlayerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_ActivePlayerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public ActivePlayerActions @ActivePlayer => new ActivePlayerActions(this);

    // ManagerPlayer
    private readonly InputActionMap m_ManagerPlayer;
    private List<IManagerPlayerActions> m_ManagerPlayerActionsCallbackInterfaces = new List<IManagerPlayerActions>();
    private readonly InputAction m_ManagerPlayer_Move;
    private readonly InputAction m_ManagerPlayer_Interact;
    private readonly InputAction m_ManagerPlayer_Cycle;
    private readonly InputAction m_ManagerPlayer_Ping;
    private readonly InputAction m_ManagerPlayer_Zoom;
    private readonly InputAction m_ManagerPlayer_Deselect;
    public struct ManagerPlayerActions
    {
        private @KBMandController m_Wrapper;
        public ManagerPlayerActions(@KBMandController wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_ManagerPlayer_Move;
        public InputAction @Interact => m_Wrapper.m_ManagerPlayer_Interact;
        public InputAction @Cycle => m_Wrapper.m_ManagerPlayer_Cycle;
        public InputAction @Ping => m_Wrapper.m_ManagerPlayer_Ping;
        public InputAction @Zoom => m_Wrapper.m_ManagerPlayer_Zoom;
        public InputAction @Deselect => m_Wrapper.m_ManagerPlayer_Deselect;
        public InputActionMap Get() { return m_Wrapper.m_ManagerPlayer; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ManagerPlayerActions set) { return set.Get(); }
        public void AddCallbacks(IManagerPlayerActions instance)
        {
            if (instance == null || m_Wrapper.m_ManagerPlayerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_ManagerPlayerActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @Interact.started += instance.OnInteract;
            @Interact.performed += instance.OnInteract;
            @Interact.canceled += instance.OnInteract;
            @Cycle.started += instance.OnCycle;
            @Cycle.performed += instance.OnCycle;
            @Cycle.canceled += instance.OnCycle;
            @Ping.started += instance.OnPing;
            @Ping.performed += instance.OnPing;
            @Ping.canceled += instance.OnPing;
            @Zoom.started += instance.OnZoom;
            @Zoom.performed += instance.OnZoom;
            @Zoom.canceled += instance.OnZoom;
            @Deselect.started += instance.OnDeselect;
            @Deselect.performed += instance.OnDeselect;
            @Deselect.canceled += instance.OnDeselect;
        }

        private void UnregisterCallbacks(IManagerPlayerActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @Interact.started -= instance.OnInteract;
            @Interact.performed -= instance.OnInteract;
            @Interact.canceled -= instance.OnInteract;
            @Cycle.started -= instance.OnCycle;
            @Cycle.performed -= instance.OnCycle;
            @Cycle.canceled -= instance.OnCycle;
            @Ping.started -= instance.OnPing;
            @Ping.performed -= instance.OnPing;
            @Ping.canceled -= instance.OnPing;
            @Zoom.started -= instance.OnZoom;
            @Zoom.performed -= instance.OnZoom;
            @Zoom.canceled -= instance.OnZoom;
            @Deselect.started -= instance.OnDeselect;
            @Deselect.performed -= instance.OnDeselect;
            @Deselect.canceled -= instance.OnDeselect;
        }

        public void RemoveCallbacks(IManagerPlayerActions instance)
        {
            if (m_Wrapper.m_ManagerPlayerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IManagerPlayerActions instance)
        {
            foreach (var item in m_Wrapper.m_ManagerPlayerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_ManagerPlayerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public ManagerPlayerActions @ManagerPlayer => new ManagerPlayerActions(this);

    // StorySceneConfirms
    private readonly InputActionMap m_StorySceneConfirms;
    private List<IStorySceneConfirmsActions> m_StorySceneConfirmsActionsCallbackInterfaces = new List<IStorySceneConfirmsActions>();
    private readonly InputAction m_StorySceneConfirms_GamepadConfirm;
    private readonly InputAction m_StorySceneConfirms_EnterConfirm;
    public struct StorySceneConfirmsActions
    {
        private @KBMandController m_Wrapper;
        public StorySceneConfirmsActions(@KBMandController wrapper) { m_Wrapper = wrapper; }
        public InputAction @GamepadConfirm => m_Wrapper.m_StorySceneConfirms_GamepadConfirm;
        public InputAction @EnterConfirm => m_Wrapper.m_StorySceneConfirms_EnterConfirm;
        public InputActionMap Get() { return m_Wrapper.m_StorySceneConfirms; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(StorySceneConfirmsActions set) { return set.Get(); }
        public void AddCallbacks(IStorySceneConfirmsActions instance)
        {
            if (instance == null || m_Wrapper.m_StorySceneConfirmsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_StorySceneConfirmsActionsCallbackInterfaces.Add(instance);
            @GamepadConfirm.started += instance.OnGamepadConfirm;
            @GamepadConfirm.performed += instance.OnGamepadConfirm;
            @GamepadConfirm.canceled += instance.OnGamepadConfirm;
            @EnterConfirm.started += instance.OnEnterConfirm;
            @EnterConfirm.performed += instance.OnEnterConfirm;
            @EnterConfirm.canceled += instance.OnEnterConfirm;
        }

        private void UnregisterCallbacks(IStorySceneConfirmsActions instance)
        {
            @GamepadConfirm.started -= instance.OnGamepadConfirm;
            @GamepadConfirm.performed -= instance.OnGamepadConfirm;
            @GamepadConfirm.canceled -= instance.OnGamepadConfirm;
            @EnterConfirm.started -= instance.OnEnterConfirm;
            @EnterConfirm.performed -= instance.OnEnterConfirm;
            @EnterConfirm.canceled -= instance.OnEnterConfirm;
        }

        public void RemoveCallbacks(IStorySceneConfirmsActions instance)
        {
            if (m_Wrapper.m_StorySceneConfirmsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IStorySceneConfirmsActions instance)
        {
            foreach (var item in m_Wrapper.m_StorySceneConfirmsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_StorySceneConfirmsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public StorySceneConfirmsActions @StorySceneConfirms => new StorySceneConfirmsActions(this);
    private int m_ControllerPlayerSchemeIndex = -1;
    public InputControlScheme ControllerPlayerScheme
    {
        get
        {
            if (m_ControllerPlayerSchemeIndex == -1) m_ControllerPlayerSchemeIndex = asset.FindControlSchemeIndex("ControllerPlayer");
            return asset.controlSchemes[m_ControllerPlayerSchemeIndex];
        }
    }
    private int m_KBMPlayerSchemeIndex = -1;
    public InputControlScheme KBMPlayerScheme
    {
        get
        {
            if (m_KBMPlayerSchemeIndex == -1) m_KBMPlayerSchemeIndex = asset.FindControlSchemeIndex("KBMPlayer");
            return asset.controlSchemes[m_KBMPlayerSchemeIndex];
        }
    }
    public interface IActivePlayerActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnRun(InputAction.CallbackContext context);
        void OnLook(InputAction.CallbackContext context);
        void OnAim(InputAction.CallbackContext context);
        void OnAttack(InputAction.CallbackContext context);
        void OnInteract(InputAction.CallbackContext context);
        void OnHeal(InputAction.CallbackContext context);
        void OnSwap(InputAction.CallbackContext context);
        void OnPing(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnCrouch(InputAction.CallbackContext context);
    }
    public interface IManagerPlayerActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnInteract(InputAction.CallbackContext context);
        void OnCycle(InputAction.CallbackContext context);
        void OnPing(InputAction.CallbackContext context);
        void OnZoom(InputAction.CallbackContext context);
        void OnDeselect(InputAction.CallbackContext context);
    }
    public interface IStorySceneConfirmsActions
    {
        void OnGamepadConfirm(InputAction.CallbackContext context);
        void OnEnterConfirm(InputAction.CallbackContext context);
    }
}
